/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;

public class bantuan3 extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public bantuan3() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getNext() {
        return b_next;
    }
    public JButton getBack() {
        return b_back;
    }

    public JButton getClose() {
        return b_x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_next = new javax.swing.JButton();
        b_back = new javax.swing.JButton();
        b_x = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_next.setBorderPainted(false);
        b_next.setContentAreaFilled(false);
        getContentPane().add(b_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 610, 80, 60));

        b_back.setBorderPainted(false);
        b_back.setContentAreaFilled(false);
        getContentPane().add(b_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 523, 70, 70));

        b_x.setBorderPainted(false);
        b_x.setContentAreaFilled(false);
        getContentPane().add(b_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bantuan/help1.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bantuan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bantuan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bantuan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bantuan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bantuan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_back;
    private javax.swing.JButton b_next;
    private javax.swing.JButton b_x;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
