/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *

 */
public class koperasi extends javax.swing.JFrame {

    /**
     * Creates new form tokoPenjualanProduk
     */
    public koperasi() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

     public JLabel getLblKoin() {
        return lblKoin;
    }
    public JLabel getLblJumlah() {
        return lblJumlah;
    }
     public JButton getBtnTambah() {
        return btnTambah;
    }

    public JButton getBtnKurang() {
        return btnKurang;
    }

    public JButton getBtnJual() {
        return btnJual;
    }
    public JButton getBtnKembali() {
        return btnKembali;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJumlah = new javax.swing.JLabel();
        lblKoin = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnJual = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJumlah.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblJumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJumlah.setText("Jumlah");
        getContentPane().add(lblJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 70, 40));

        lblKoin.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKoin.setText("Koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, 70, 40));

        btnTambah.setBorderPainted(false);
        btnTambah.setContentAreaFilled(false);
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setFocusable(false);
        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 40, 60));

        btnKurang.setBorderPainted(false);
        btnKurang.setContentAreaFilled(false);
        btnKurang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKurang.setFocusable(false);
        btnKurang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 50, 60));

        btnJual.setBorderPainted(false);
        btnJual.setContentAreaFilled(false);
        btnJual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJual.setFocusable(false);
        btnJual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 120, 60));

        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        btnKembali.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnKembali.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isitoko/koperasi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(koperasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new koperasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJual;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKoin;
    // End of variables declaration//GEN-END:variables
}
