/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;


public class lahan extends javax.swing.JFrame {

    /**
     * Creates new form sawah
     */
    public lahan() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnAir() {
        return btnAir;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JButton getBtnKotak1() {
        return btnKotak1;
    }

    public JButton getBtnKotak2() {
        return btnKotak2;
    }

    public JButton getBtnKotak3() {
        return btnKotak3;
    }

    public JButton getBtnKotak4() {
        return btnKotak4;
    }

    public JButton getBtnKotak5() {
        return btnKotak5;
    }

    public JButton getBtnKotak6() {
        return btnKotak6;
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }

    public JLabel getLblJagung() {
        return lblBibitJagung;
    }
    public JLabel getLblPadi() {
        return lblBibitPadi;
    }
    public JLabel getLblTebu() {
        return lblBibitTebu;
    }
    public JLabel getLblPestisida() {
        return lblPestisida;
    }
    public JLabel getLblPupuk() {
        return lblPupuk;
    }

    public JLabel getLblNotif() {
        return lblNotif;
    }

    public JLabel getLblNotif1() {
        return lblNotif1;
    }

    public JLabel getLblNotif2() {
        return lblNotif2;
    }

    public JLabel getLblNotif3() {
        return lblNotif3;
    }

    public JLabel getLblNotif4() {
        return lblNotif4;
    }

    public JLabel getLblNotif5() {
        return lblNotif5;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotif5 = new javax.swing.JLabel();
        lblNotif4 = new javax.swing.JLabel();
        lblNotif3 = new javax.swing.JLabel();
        lblNotif2 = new javax.swing.JLabel();
        lblNotif1 = new javax.swing.JLabel();
        lblNotif = new javax.swing.JLabel();
        btnAir = new javax.swing.JButton();
        btnKotak6 = new javax.swing.JButton();
        btnKotak5 = new javax.swing.JButton();
        btnKotak4 = new javax.swing.JButton();
        btnKotak3 = new javax.swing.JButton();
        btnKotak2 = new javax.swing.JButton();
        btnKotak1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        lblKoin = new javax.swing.JLabel();
        lblBibitPadi = new javax.swing.JLabel();
        lblBibitTebu = new javax.swing.JLabel();
        lblPestisida = new javax.swing.JLabel();
        lblPupuk = new javax.swing.JLabel();
        lblBibitJagung = new javax.swing.JLabel();
        statusBar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNotif5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif5.setToolTipText("");
        getContentPane().add(lblNotif5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, -1, -1));

        lblNotif4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif4.setToolTipText("");
        getContentPane().add(lblNotif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, -1, -1));

        lblNotif3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif3.setToolTipText("");
        getContentPane().add(lblNotif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        lblNotif2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif2.setToolTipText("");
        getContentPane().add(lblNotif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, -1, -1));

        lblNotif1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif1.setToolTipText("");
        getContentPane().add(lblNotif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        lblNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/notif air.png"))); // NOI18N
        lblNotif.setToolTipText("");
        getContentPane().add(lblNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        btnAir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tblSiram.png"))); // NOI18N
        btnAir.setBorderPainted(false);
        btnAir.setContentAreaFilled(false);
        btnAir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAir.setFocusable(false);
        btnAir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/tblSiram hover.png"))); // NOI18N
        getContentPane().add(btnAir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 510, -1, 210));

        btnKotak6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/ns3.png"))); // NOI18N
        btnKotak6.setBorderPainted(false);
        btnKotak6.setContentAreaFilled(false);
        btnKotak6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak6.setFocusable(false);
        btnKotak6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, -1, -1));

        btnKotak5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/ns3.png"))); // NOI18N
        btnKotak5.setBorderPainted(false);
        btnKotak5.setContentAreaFilled(false);
        btnKotak5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak5.setFocusable(false);
        btnKotak5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, -1, -1));

        btnKotak4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/ns3.png"))); // NOI18N
        btnKotak4.setBorderPainted(false);
        btnKotak4.setContentAreaFilled(false);
        btnKotak4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak4.setFocusable(false);
        btnKotak4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        btnKotak3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/ns3.png"))); // NOI18N
        btnKotak3.setBorderPainted(false);
        btnKotak3.setContentAreaFilled(false);
        btnKotak3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak3.setFocusable(false);
        btnKotak3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, -1, -1));

        btnKotak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/ns3.png"))); // NOI18N
        btnKotak2.setBorderPainted(false);
        btnKotak2.setContentAreaFilled(false);
        btnKotak2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak2.setFocusable(false);
        btnKotak2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        btnKotak1.setBorderPainted(false);
        btnKotak1.setContentAreaFilled(false);
        btnKotak1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKotak1.setDefaultCapable(false);
        btnKotak1.setFocusable(false);
        btnKotak1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnKotak1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnKotak1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnKotak1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnKotak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 110, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/lhn.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/lhn.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 460, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/lhn.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/lhn.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/lhn.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/lhn.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/x.png"))); // NOI18N
        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 70, 60));

        lblKoin.setFont(new java.awt.Font("Bw Surco DEMO", 1, 18)); // NOI18N
        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKoin.setText("Koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 120, 40));

        lblBibitPadi.setFont(new java.awt.Font("Bw Surco DEMO", 1, 14)); // NOI18N
        lblBibitPadi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBibitPadi.setText("Padi");
        getContentPane().add(lblBibitPadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 120, 40));

        lblBibitTebu.setFont(new java.awt.Font("Bw Surco DEMO", 1, 14)); // NOI18N
        lblBibitTebu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBibitTebu.setText("Tebu");
        getContentPane().add(lblBibitTebu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 120, 40));

        lblPestisida.setFont(new java.awt.Font("Bw Surco DEMO", 1, 14)); // NOI18N
        lblPestisida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPestisida.setText("Pestisida");
        getContentPane().add(lblPestisida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 120, 40));

        lblPupuk.setFont(new java.awt.Font("Bw Surco DEMO", 1, 14)); // NOI18N
        lblPupuk.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPupuk.setText("Pupuk");
        getContentPane().add(lblPupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 360, 120, 40));

        lblBibitJagung.setFont(new java.awt.Font("Bw Surco DEMO", 1, 14)); // NOI18N
        lblBibitJagung.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBibitJagung.setText("Jagung");
        getContentPane().add(lblBibitJagung, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 120, 40));

        statusBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/rp.png"))); // NOI18N
        getContentPane().add(statusBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/jmlhjagung.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 180, 128, 44));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/jmlhtebu.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 128, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/jmlhpest.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 300, 128, 44));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/jmlhpupuk.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 360, 128, 44));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/jmlhpadi.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/bgjmlh.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isisawah/xxx.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAir;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKotak1;
    private javax.swing.JButton btnKotak2;
    private javax.swing.JButton btnKotak3;
    private javax.swing.JButton btnKotak4;
    private javax.swing.JButton btnKotak5;
    private javax.swing.JButton btnKotak6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBibitJagung;
    private javax.swing.JLabel lblBibitPadi;
    private javax.swing.JLabel lblBibitTebu;
    private javax.swing.JLabel lblKoin;
    private javax.swing.JLabel lblNotif;
    private javax.swing.JLabel lblNotif1;
    private javax.swing.JLabel lblNotif2;
    private javax.swing.JLabel lblNotif3;
    private javax.swing.JLabel lblNotif4;
    private javax.swing.JLabel lblNotif5;
    private javax.swing.JLabel lblPestisida;
    private javax.swing.JLabel lblPupuk;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables
}
