/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;


public class map extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public map() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }    

    public JButton getBtnGudang() {
        return btnGudang;
    }

    public JButton getBtnKoperasi() {
        return btnKoperasi;
    }


    public JButton getBtnSawah1() {
        return btnSawah1;
    }

    public JButton getBtnToko() {
        return btnToko;
    }

    public JButton getBtnLogOut() {
        return btnLogOut;
    }

    public JLabel getLabelUsername() {
        return labelUsername;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKoin = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnToko = new javax.swing.JButton();
        btnGudang = new javax.swing.JButton();
        btnKoperasi = new javax.swing.JButton();
        btnSawah1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKoin.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKoin.setText("Koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 50, 100, 30));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/logout.png"))); // NOI18N
        btnLogOut.setBorderPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setFocusable(false);
        getContentPane().add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 620, 70, 70));

        labelUsername.setFont(new java.awt.Font("Bebas Neue", 0, 30)); // NOI18N
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername.setText("username");
        getContentPane().add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/rp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, -1, -1));

        btnToko.setBorderPainted(false);
        btnToko.setContentAreaFilled(false);
        btnToko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToko.setFocusable(false);
        getContentPane().add(btnToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, 340, 340));

        btnGudang.setBorderPainted(false);
        btnGudang.setContentAreaFilled(false);
        btnGudang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGudang.setFocusable(false);
        getContentPane().add(btnGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 260, 260));

        btnKoperasi.setBorderPainted(false);
        btnKoperasi.setContentAreaFilled(false);
        btnKoperasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKoperasi.setFocusable(false);
        getContentPane().add(btnKoperasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 260, 270));

        btnSawah1.setBorderPainted(false);
        btnSawah1.setContentAreaFilled(false);
        btnSawah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSawah1.setFocusable(false);
        getContentPane().add(btnSawah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 69, 520, 340));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/koperasi.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/toko.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/lahan.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/map/bg.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGudang;
    private javax.swing.JButton btnKoperasi;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSawah1;
    private javax.swing.JButton btnToko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel lblKoin;
    // End of variables declaration//GEN-END:variables
}
