/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package v;

import javax.swing.JButton;
import javax.swing.JLabel;


public class tokotani extends javax.swing.JFrame {

    /**
     * Creates new form koperasi
     */
    public tokotani() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public JButton getBtnItem1() {
        return btnItem1;
    }

    public JButton getBtnItem2() {
        return btnItem2;
    }

    public JButton getBtnItem3() {
        return btnItem3;
    }

    public JButton getBtnItem4() {
        return btnItem4;
    }
    public JButton getBtnItem5() {
        return btnItem5;
    }

    public JButton getBtnKembali() {
        return btnKembali;
    }

    public JLabel getLblKoin() {
        return lblKoin;
    }

  

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JButton();
        btnItem1 = new javax.swing.JButton();
        btnItem2 = new javax.swing.JButton();
        btnItem3 = new javax.swing.JButton();
        btnItem4 = new javax.swing.JButton();
        btnItem5 = new javax.swing.JButton();
        lblKoin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKembali.setBorderPainted(false);
        btnKembali.setContentAreaFilled(false);
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.setFocusable(false);
        btnKembali.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnKembali.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, 70));

        btnItem1.setBorderPainted(false);
        btnItem1.setContentAreaFilled(false);
        btnItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnItem1.setFocusable(false);
        btnItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 70, 40));

        btnItem2.setBorderPainted(false);
        btnItem2.setContentAreaFilled(false);
        btnItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnItem2.setFocusable(false);
        btnItem2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 70, 40));

        btnItem3.setBorderPainted(false);
        btnItem3.setContentAreaFilled(false);
        btnItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnItem3.setFocusable(false);
        btnItem3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 90, 40));

        btnItem4.setBorderPainted(false);
        btnItem4.setContentAreaFilled(false);
        btnItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnItem4.setDefaultCapable(false);
        btnItem4.setFocusable(false);
        btnItem4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 70, 40));

        btnItem5.setBorderPainted(false);
        btnItem5.setContentAreaFilled(false);
        btnItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnItem5.setDefaultCapable(false);
        btnItem5.setFocusable(false);
        btnItem5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnItem5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(btnItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 80, 40));

        lblKoin.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        lblKoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKoin.setText("koin");
        getContentPane().add(lblKoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 80, 140, 35));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/isiKoperasi/tokotani.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tokotani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tokotani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tokotani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tokotani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tokotani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItem1;
    private javax.swing.JButton btnItem2;
    private javax.swing.JButton btnItem3;
    private javax.swing.JButton btnItem4;
    private javax.swing.JButton btnItem5;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblKoin;
    // End of variables declaration//GEN-END:variables
}
