/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tani.go;

import javax.swing.JButton;

/**
 *
 * @author Deddy
 */
public class framepilih extends javax.swing.JFrame {

    /**
     * Creates new form framepilih
     */
    public framepilih() {
        this.setUndecorated(true);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        initComponents();
        setLocationRelativeTo(this);
        this.setSize(370, 190);
    }

    public JButton b_mulaibaru() {
        return b_mulaibaru;
    }

    public JButton b_lanjut() {
        return b_lanjut;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_mulaibaru = new javax.swing.JButton();
        b_lanjut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_mulaibaru.setBorderPainted(false);
        b_mulaibaru.setContentAreaFilled(false);
        getContentPane().add(b_mulaibaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, 50));

        b_lanjut.setToolTipText("");
        b_lanjut.setBorderPainted(false);
        b_lanjut.setContentAreaFilled(false);
        getContentPane().add(b_lanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambarplay/play.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framepilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framepilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framepilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framepilih.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framepilih().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_lanjut;
    private javax.swing.JButton b_mulaibaru;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
